/*
 * test-openapi API
 *
 * template for test-openapi API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
)

// ItemApiRouter defines the required methods for binding the api requests to a responses for the ItemApi
// The ItemApiRouter implementation should parse necessary information from the http request,
// pass the data to a ItemApiServicer to perform the required actions, then write the service results to the http response.
type ItemApiRouter interface {
	GetItemById(http.ResponseWriter, *http.Request)
	ItemsGet(http.ResponseWriter, *http.Request)
	UpdateItemWithForm(http.ResponseWriter, *http.Request)
}

// KoalaApiRouter defines the required methods for binding the api requests to a responses for the KoalaApi
// The KoalaApiRouter implementation should parse necessary information from the http request,
// pass the data to a KoalaApiServicer to perform the required actions, then write the service results to the http response.
type KoalaApiRouter interface {
	GetKoala(http.ResponseWriter, *http.Request)
}

// ItemApiServicer defines the api actions for the ItemApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ItemApiServicer interface {
	GetItemById(context.Context, int64) (ImplResponse, error)
	ItemsGet(context.Context) (ImplResponse, error)
	UpdateItemWithForm(context.Context, int64, int64, string) (ImplResponse, error)
}

// KoalaApiServicer defines the api actions for the KoalaApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type KoalaApiServicer interface {
	GetKoala(context.Context) (ImplResponse, error)
}
