/*
 * test-openapi API
 *
 * template for test-openapi API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"errors"
	"net/http"
)

// ItemApiService is a service that implements the logic for the ItemApiServicer
// This service should implement the business logic for every endpoint for the ItemApi API.
// Include any external packages or services that will be required by this service.
type ItemApiService struct {
}

// NewItemApiService creates a default api service
func NewItemApiService() ItemApiServicer {
	return &ItemApiService{}
}

// GetItemById - Find item by ID
func (s *ItemApiService) GetItemById(ctx context.Context, itemId int64) (ImplResponse, error) {
	// TODO - update GetItemById with the required logic for this service method.
	// Add api_item_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Item{}) or use other options such as http.Ok ...
	//return Response(200, Item{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetItemById method not implemented")
}

// ItemsGet -
func (s *ItemApiService) ItemsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ItemsGet with the required logic for this service method.
	// Add api_item_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Item{}) or use other options such as http.Ok ...
	//return Response(200, []Item{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ItemsGet method not implemented")
}

// UpdateItemWithForm - Updates a item with form data
func (s *ItemApiService) UpdateItemWithForm(ctx context.Context, itemId int64, id int64, name string) (ImplResponse, error) {
	// TODO - update UpdateItemWithForm with the required logic for this service method.
	// Add api_item_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	//return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateItemWithForm method not implemented")
}
