/*
 * test-openapi API
 *
 * template for test-openapi API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"errors"
	"net/http"
)

// KoalaApiService is a service that implements the logic for the KoalaApiServicer
// This service should implement the business logic for every endpoint for the KoalaApi API.
// Include any external packages or services that will be required by this service.
type KoalaApiService struct {
}

// NewKoalaApiService creates a default api service
func NewKoalaApiService() KoalaApiServicer {
	return &KoalaApiService{}
}

// GetKoala -
func (s *KoalaApiService) GetKoala(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetKoala with the required logic for this service method.
	// Add api_koala_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, string{}) or use other options such as http.Ok ...
	//return Response(200, string{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetKoala method not implemented")
}
